### ISSUE TITLE
Training Script not Generating Tokenizer Files

### ISSUE THREAD

**Issue by antitheos** [clip-italian/clip-italian#12]
this is probably user error and i am new to python
i am following instructions at [https://github.com/clip-italian/clip-italian/tree/master/hybrid_clip](https://github.com/clip-italian/clip-italian/tree/master/hybrid_clip)
trying to run the training code, it generates the subfolder with:
 _**config.json**_ 
_**flax_model.msgpack**_

however the other files as seen at [https://huggingface.co/clip-italian/clip-italian/tree/main](https://huggingface.co/clip-italian/clip-italian/tree/main) dont get created eg
 _**tokenizer_config.json
tokenizer.json, 
preprocessor_config.json
special_tokens_map.json
vocab.txt**_

**Comment by vinid** [comment]
Hello!

Yea those files have been added to support the pytroch version if I recall correctly. Indeed they were added by the HF team a [couple of months after the project](https://huggingface.co/clip-italian/clip-italian/commit/ec24f9388c45cbc404a12d94038c623425f99a31)

@g8a9 do you confirm?

**Comment by g8a9** [comment]
Hi! Correct, the current training script does not create the preprocessor and tokenizer configuration files. The ones on the HF hub were added later to the model.

Anyways, those should be standard files generated by the vision preprocessor and the language tokenizer (HF classes) so you can refer to them if you need them for a pretrained model, or to save and include them during training.

**Comment by antitheos** [comment]
thought as much, wanted to make sure
thanx for clarifying.

**Comment by g8a9** [comment]
You're welcome!
