### ISSUE TITLE
Finetuning for other languages

### ISSUE THREAD

**Issue by RaiAmanRai** [clip-italian/clip-italian#15]
Hi @vinid @g8a9 is it possible to use this same repo to finetune the clip model for other langusges, and if so how can I use it

**Comment by g8a9** [comment]
Hi @RaiAmanRai, yes, you can use this repo to fine-tune the model in other languages.
You might want to take a look at our [runner bash script](https://github.com/clip-italian/clip-italian/blob/master/hybrid_clip/run_training.sh) where we call the main training script.

Apart from changing some hparams to fit your computational resources, you might want to change the pretrained text encoder, which is now set to an Italian BERT checkpoint (`TEXT_ENCODER="dbmdz/bert-base-italian-xxl-uncased"`) with something in your target language.
