### ISSUE TITLE
Getting error when running the last cell of CLIP_italian_ImageNet_Zero_Shot_Evaluation_.ipynb

### ISSUE THREAD

**Issue by shoaibahmadse** [clip-italian/clip-italian#16]
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

**Comment by vinid** [comment]
Hello!!

I'd use the more recent colab notebook based on torch/the new huggingface encoders:

https://colab.research.google.com/drive/1SSddpjohAqRS_XxJvwz5HN1YFPevVJmy?usp=sharing

**Comment by g8a9** [comment]
Hey, I think this is related to #17, can you take a look at https://github.com/clip-italian/clip-italian/issues/17#issuecomment-1410440874 and see if that works for you?
