### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument '_do_init'

### ISSUE THREAD

**Issue by alhuri** [clip-italian/clip-italian#18]
I am trying to unfreeze and train from a checkpoint however I am getting an error when running the bellow snippet.

```
 if args.run_from_checkpoint is not None:
        with open(f"{args.run_from_checkpoint}/config.json", "r") as fp:
            config_dict = json.load(fp)
        config_dict["vision_config"]["model_type"] = "clip"
        config = HybridCLIPConfig(**config_dict)
        model = FlaxHybridCLIP.from_pretrained(
            args.run_from_checkpoint,
            seed=training_args.seed,
            dtype=getattr(jnp, model_args.dtype),
            config=config,
            freeze_backbones=args.freeze_backbones
        )
```
The error message

```
`text_config` is `None`. Initializing the `CLIPTextConfig` with default values.
`vision_config` is `None`. initializing the `CLIPVisionConfig` with default values.
loading weights file freeze/18/flax_model.msgpack
Traceback (most recent call last):
  File "run_hybrid_clip.py", line 831, in <module>
    main()
  File "run_hybrid_clip.py", line 528, in main
    model = FlaxHybridCLIP.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_flax_utils.py", line 807, in from_pretrained
    model = cls(config, *model_args, _do_init=_do_init, **model_kwargs)
  File "/home/ubuntu/modeling_hybrid_clip.py", line 148, in __init__
    module = self.module_class(config=config, dtype=dtype, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_do_init'
```

**Comment by alhuri** [comment]
@g8a9

**Comment by vinid** [comment]
I'll look into this but I'd suggest you to look at the original huggingface code for training Contrastive models. I think it might be more up to date with the recent library change

**Comment by g8a9** [comment]
Hi, can you give us more details on what kind of model you are using? Having the full snippet that causes the error could help. In the meantime, please take a look at the new way of instantiating CLIP-Italian with PyTorch weights and the new HuggingFace classes in our [official notebook](https://colab.research.google.com/drive/1SSddpjohAqRS_XxJvwz5HN1YFPevVJmy?usp=sharing).

**Comment by alhuri** [comment]
I'm trying to run your modified version of run_hybrid_clip.py
the part that causes the error is the below snippet more specifically the 6th line

```
 if args.run_from_checkpoint is not None:
        with open(f"{args.run_from_checkpoint}/config.json", "r") as fp:
            config_dict = json.load(fp)
        config_dict["vision_config"]["model_type"] = "clip"
        config = HybridCLIPConfig(**config_dict)
        model = FlaxHybridCLIP.from_pretrained(
            args.run_from_checkpoint,
            seed=training_args.seed,
            dtype=getattr(jnp, model_args.dtype),
            config=config,
            freeze_backbones=args.freeze_backbones
        )
```

**Comment by vinid** [comment]
Most likely it's an huggingface version problem. You can use this: https://github.com/huggingface/transformers/tree/main/examples/pytorch/contrastive-image-text

**Comment by alhuri** [comment]
@4rtemi5 how can I load a FlaxHybridCLIP trained model on the modified script?

**Comment by vinid** [comment]
You need to downgrade to past versions of the transformers package (probably around 4.10). But I think the best thing to do is to use https://github.com/huggingface/transformers/tree/main/examples/pytorch/contrastive-image-text

**Comment by alhuri** [comment]
I'm getting the below error
```
vision_config_dict is None. initializing the CLIPVisionConfig with default values.
loading weights file freeze/18/flax_model.msgpack
Traceback (most recent call last):
  File "run_hybrid_clip.py", line 833, in <module>
    main()
  File "run_hybrid_clip.py", line 530, in main
    model = FlaxHybridCLIP.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_flax_utils.py", line 350, in from_pretrained
    state = from_bytes(cls, state_f.read())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flax/serialization.py", line 359, in from_bytes
    state_dict = msgpack_restore(encoded_bytes)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flax/serialization.py", line 342, in msgpack_restore
    return msgpack.unpackb(
  File "msgpack/_unpacker.pyx", line 208, in msgpack._unpacker.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

**Comment by vinid** [comment]
is this with the downgraded transformers version?

**Comment by alhuri** [comment]
> is this with the downgraded transformers version?

Yes

**Comment by vinid** [comment]
Mmm, not sure which is the correct version. 
Will try to look into this, but my current suggestion is to use the scripts in the transformers library

**Comment by alhuri** [comment]
> Mmm, not sure which is the correct version. Will try to look into this, but my current suggestion is to use the scripts in the transformers library

I used the versions stated here https://github.com/huggingface/transformers/issues/12513 for all the libraries. no luck!

**Comment by humanely** [comment]
Any luck?
