### ISSUE TITLE
Load pretrained model

### ISSUE THREAD

**Issue by lakatosgabor** [clip-italian/clip-italian#20]
Hi!

I successfully continued teaching the clip on my own data.

Created flax_model.msgpack and config.json.

How can I test the model?

Thanks,
G.

**Comment by vinid** [comment]
Hi!

Did you already try to use one of our evaluation notebooks?

**Comment by lakatosgabor** [comment]
@vinid Thank you your fast answer!

Yes, of course. I try run the CLIP_Image_Retrieval_and_MRR file.

I get the below error:

Traceback (most recent call last):
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/test_model.py", line 198, in <module>
    image_features = precompute_image_features(loader)
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/test_model.py", line 149, in precompute_image_features
    features = image_model(images)
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/test_model.py", line 76, in <lambda>
    image_model = lambda images: se_image_model.encode(images, batch_size=1024, convert_to_tensor=True, show_progress_bar=False).cpu().detach().numpy()
  File "/home/keplab/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 161, in encode
    features = self.tokenize(sentences_batch)
  File "/home/keplab/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 319, in tokenize
    return self._first_module().tokenize(texts)
  File "/home/keplab/.local/lib/python3.10/site-packages/sentence_transformers/models/CLIPModel.py", line 71, in tokenize
    inputs = self.processor(text=texts_values, images=images, return_tensors="pt", padding=True)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/models/clip/processing_clip.py", line 99, in __call__
    encoding = self.tokenizer(text, return_tensors=return_tensors, **kwargs)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2530, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2588, in _call_one
    raise ValueError(
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Thanks your help!

**Comment by lakatosgabor** [comment]
@vinid  Thank you your fast answer!

Yes, of course. I try run the CLIP_Image_Retrieval_and_MRR file.

I get the below error, when i run this code:

MODEL_TYPE = 'clip_italian'

`if MODEL_TYPE == 'mClip':
    from sentence_transformers import SentenceTransformer
    # Here we load the multilingual CLIP model. Note, this model can only encode text.
    # If you need embeddings for images, you must load the 'clip-ViT-B-32' model
    se_language_model = SentenceTransformer('clip-ViT-B-32-multilingual-v1')
    se_image_model = SentenceTransformer('clip-ViT-B-32')
    language_model = lambda queries: se_language_model.encode(queries, convert_to_tensor=True, show_progress_bar=False).cpu().detach().numpy()
    image_model = lambda images: se_image_model.encode(images, batch_size=1024, convert_to_tensor=True, show_progress_bar=False).cpu().detach().numpy()
elif MODEL_TYPE == 'clip_italian':
    import jax
    from jax import numpy as jnp
    TOKENIZER_NAME = "dbmdz/bert-base-italian-xxl-uncased"
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_NAME, cache_dir=None, use_fast=True)
    model = FlaxHybridCLIP.from_pretrained("clip-italian/clip-italian")
    def tokenize(texts):
        inputs = tokenizer(texts, max_length=96, padding="max_length", return_tensors="np")
        return inputs['input_ids'], inputs['attention_mask']

    language_model = lambda queries: np.asarray(model.get_text_features(*tokenize(queries)))
    image_model = lambda images: np.asarray(model.get_image_features(images.permute(0, 2, 3, 1).numpy(),))
`



ERROR:
You are using a model of type vision-text-dual-encoder to instantiate a model of type hybrid-clip. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/test_model.py", line 78, in <module>
    model = FlaxHybridCLIP.from_pretrained("clip-italian/clip-italian")
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/modeling_flax_utils.py", line 639, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 553, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 696, in from_dict
    config = cls(**config_dict)
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/configuration_hybrid_clip.py", line 79, in __init__
    self.vision_config = AutoConfig.for_model(vision_model_type, **vision_config)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 804, in for_model
    raise ValueError(
ValueError: Unrecognized model identifier: clip_vision_model. Should contain one of albert, align, altclip, audio-spectrogram-transformer, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, camembert, canine, chinese_clip, clap, clip, clipseg, codegen, conditional_detr, convbert, convnext, convnextv2, ctrl, cvt, data2vec-audio, data2vec-text, data2vec-vision, deberta, deberta-v2, decision_transformer, deformable_detr, deit, deta, detr, dinat, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encoder-decoder, ernie, ernie_m, esm, flaubert, flava, fnet, fsmt, funnel, git, glpn, gpt-sw3, gpt2, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, graphormer, groupvit, hubert, ibert, imagegpt, informer, jukebox, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, longformer, longt5, luke, lxmert, m2m_100, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, megatron-bert, mgp-str, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mpnet, mt5, mvp, nat, nezha, nystromformer, oneformer, openai-gpt, opt, owlvit, pegasus, pegasus_x, perceiver, plbart, poolformer, prophetnet, qdqbert, rag, realm, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, segformer, sew, sew-d, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, trajectory_transformer, transfo-xl, trocr, tvlt, unispeech, unispeech-sat, upernet, van, videomae, vilt, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, wav2vec2, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso

**Comment by vinid** [comment]
not really sure what could be the problem.Which version of transformers are you using?

**Comment by lakatosgabor** [comment]
@vinid 
Transformers info:

Name: transformers
Version: 4.29.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/keplab/.local/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, tokenizers, tqdm
Required-by: sentence-transformers

**Comment by vinid** [comment]
This version is probably too recent and that might be an issue.

in the trace you posted I see:

```You are using a model of type vision-text-dual-encoder to instantiate a model of type hybrid-clip. This is not supported for all configurations of models and can yield errors.```

I'd use the pytorch version of the model if possible

**Comment by lakatosgabor** [comment]
@vinid 
wich transformers version is correct?

how to convert to pythorch model?

**Comment by vinid** [comment]
@g8a9 any intuition on which could be the correct version? I remember we tried a couple but not sure if we ever found the correct one

**Comment by lakatosgabor** [comment]
@vinid 
I used this for the training:
python run_hybrid_clip.py \
    --output_dir ${MODEL_DIR} \
    --text_model_name_or_path="roberta-base" \
    --vision_model_name_or_path="openai/clip-vit-base-patch32" \
    --tokenizer_name="roberta-base" \
    --train_file="coco_dataset/train_dataset.json" \
    --validation_file="coco_dataset/validation_dataset.json" \
    --do_train --do_eval \
    --num_train_epochs="80" --max_seq_length 96 \
    --per_device_train_batch_size="64" \
    --per_device_eval_batch_size="64" \
    --learning_rate="5e-5" --warmup_steps="1" --weight_decay 0.1 \
    --overwrite_output_dir \
    --preprocessing_num_workers 32 \

I got two files: config.json and flax_model.msgpack. How can I run the teaching so that it is based on pytorch?

Thanks!

**Comment by vinid** [comment]
You can use this https://github.com/huggingface/transformers/tree/main/examples/pytorch/contrastive-image-text

**Comment by g8a9** [comment]
Hey, given some tests and things I remember we tried, my understanding is the following:

1. our training script creates a flax checkpoint of type `hybrid-clip`, which is now not supported anymore by HF. Hence, the only way to use a checkpoint trained with our `run_hybrid_clip.py` is by explicitly use of our class
```python
from modeling_hybrid_clip import FlaxHybridCLIP
from configuration_hybrid_clip import HybridCLIPConfig

m = FlaxHybridCLIP.from_pretrained(<your local trained model directory>)
```

2. starting from a [commit by HF](https://huggingface.co/clip-italian/clip-italian/commit/ec24f9388c45cbc404a12d94038c623425f99a31), our official config changed to support new HF classes and API @vinid. Hence, people trying to use our original flax checkpoint like @lakatosgabor running 
```python 
m = FlaxHybridCLIP.from_pretrained("clip-italian/clip-italian")
```
will have it fail since the supported type is now `VisionTextDualEncoderModel`. Since this type does have a flax variant, we should encourage people interested in using Flax, to use instead:

```python
from transformers import FlaxVisionTextDualEncoderModel
m = FlaxVisionTextDualEncoderModel.from_pretrained("clip-italian/clip-italian")
``` 
 
On your hand @lakatosgabor this means that you either 1) use in our eval script your local checkpoint which should be of `hybrid-clip` type already or 2) adapt our training script to the new `FlaxVisionTextDualEncoderModel` and train a new model of that type (changes should be minimal really) -- ofc we are happy if you could open a pull request on that.
Lastly, you could move to pytorch entirely, following the recipe already linked by @vinid (https://github.com/huggingface/transformers/tree/main/examples/pytorch/contrastive-image-text)

**Comment by lakatosgabor** [comment]
@g8a9 Thanky your fast answer!

I would like run your eval script. I run colab, and my local computer. The error is same. See below.

Run LIP_Image_Retrieval_and_MRR file.

```
/home/keplab/.local/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/home/keplab/.local/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/home/keplab/.local/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
Traceback (most recent call last):
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/test_model.py", line 78, in <module>
    model = FlaxHybridCLIP.from_pretrained("/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/mymodel/config.json")
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/modeling_flax_utils.py", line 639, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 554, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 701, in from_dict
    config = cls(**config_dict)
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/CLIP_TEST/configuration_hybrid_clip.py", line 80, in __init__
    self.vision_config = AutoConfig.for_model(vision_model_type, **vision_config)
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 836, in for_model
    raise ValueError(
ValueError: Unrecognized model identifier: clip_vision_model. Should contain one of albert, align, altclip, audio-spectrogram-transformer, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, camembert, canine, chinese_clip, clap, clip, clipseg, codegen, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, data2vec-audio, data2vec-text, data2vec-vision, deberta, deberta-v2, decision_transformer, deformable_detr, deit, deta, detr, dinat, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encoder-decoder, ernie, ernie_m, esm, flaubert, flava, fnet, focalnet, fsmt, funnel, git, glpn, gpt-sw3, gpt2, gpt_bigcode, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, graphormer, groupvit, hubert, ibert, imagegpt, informer, jukebox, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, llama, longformer, longt5, luke, lxmert, m2m_100, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, mega, megatron-bert, mgp-str, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mpnet, mt5, mvp, nat, nezha, nllb-moe, nystromformer, oneformer, open-llama, openai-gpt, opt, owlvit, pegasus, pegasus_x, perceiver, pix2struct, plbart, poolformer, prophetnet, qdqbert, rag, realm, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, rwkv, sam, segformer, sew, sew-d, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, trajectory_transformer, transfo-xl, trocr, tvlt, unispeech, unispeech-sat, upernet, van, videomae, vilt, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, wav2vec2, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso
```

**Comment by mohammad-albarham** [comment]
[requirements_shared.txt](https://github.com/clip-italian/clip-italian/files/11597261/requirements_shared.txt)

I attached my requirements and I am able to run the model correctly. I hope this will help.

@vinid  @lakatosgabor

**Comment by lakatosgabor** [comment]
Thanks everyone for your help. This is how I can use the model:

`
from transformers import FlaxVisionTextDualEncoderModel
model = FlaxVisionTextDualEncoderModel.from_pretrained("/content/drive/MyDrive/model/76")
`

**Comment by humanely** [comment]
> [requirements_shared.txt](https://github.com/clip-italian/clip-italian/files/11597261/requirements_shared.txt)
> 
> I attached my requirements and I am able to run the model correctly. I hope this will help.
> 
> @vinid @lakatosgabor

Where do you make this change in training [code]( https://github.com/clip-italian/clip-italian/blob/523e1faa75ef5fd01db5883d257468c87c9a1c2f/hybrid_clip/run_hybrid_clip.py#L538)?

**Comment by mohammad-albarham** [comment]
@humanely 

I have installed the requeirments using the attached file ([requirements_shared.txt](https://github.com/clip-italian/clip-italian/files/11597261/requirements_shared.txt)) instread of the existing file [requirements.txt](https://github.com/clip-italian/clip-italian/blob/master/requirements.txt)
