### ISSUE TITLE
How to calculate localization?

### ISSUE THREAD

**Issue by kyunghoyu** [clip-italian/clip-italian#23]
Hello!
I referred to the code you provided and successfully trained CLIP on a custom dataset.
Fortunately, following the instructions you provided, I was able to complete the training successfully.
I was able to measure the performance by referring to other Colab notebooks.

Do you have any guide sources for localization calculations?
Is there any relevance to [adaption CLIP](https://github.com/pals-ttic/adapting-CLIP)?

**Comment by vinid** [comment]
Hello!

For the localization, we also have code on the Demo/webapp!

I unfortunately don't know the method you shared, so I am not sure if they do something similar or not

**Comment by kyunghoyu** [comment]
Hello? Thank you for your response.
I found the localization code after reviewing the demo. Thank you!
