### ISSUE TITLE
Training from checkpoint

### ISSUE THREAD

**Issue by lakatosgabor** [clip-italian/clip-italian#27]
Hi Guys!

I use your article (hybrid-clip) my thesis at Uni from Hungary.

Your work is realy intrested and helpful! Thank you!

I created succesfuly a model (flax_model.msgpack).

I would like pretrained this model other dataset.

I use this commed for run:
`
#!/bin/bash

SCRIPT_DIR=.
MODEL_DIR=/mnt/Storage_2/Personal/Lakatos_Gabor/hybrid_clip/ogyei

IMAGE_ENCODER="openai/clip-vit-base-patch32"
TEXT_ENCODER="SZTAKI-HLT/hubert-base-cc"

python3 ${SCRIPT_DIR}/run_hybrid_clip.py \
    --output_dir ${MODEL_DIR} \
    --overwrite_output_dir \
    --tokenizer_name=${TEXT_ENCODER} \
    --train_file="/mnt/Storage_2/Personal/Lakatos_Gabor/train_hun.json" \
    --validation_file="/mnt/Storage_2/Personal/Lakatos_Gabor/valid_hun.json" \
    --do_train --do_eval \
    --num_train_epochs=80 --max_seq_length=96 \
    --per_device_train_batch_size=32 \
    --per_device_eval_batch_size=32 \
    --learning_rate=0.00001 --warmup_ratio=0.1 --weight_decay=0.0 \
    --preprocessing_num_workers=8 \
    --text_model_name_or_path=${TEXT_ENCODER} \
    --vision_model_name_or_path=${IMAGE_ENCODER} \
    --freeze_backbones \
    --run_from_checkpoint="/mnt/Storage_2/Personal/Lakatos_Gabor/hybrid_clip/output_data/76"

`
Get this error:

Traceback (most recent call last):
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/hybrid_clip/./run_hybrid_clip.py", line 847, in <module>
    main()
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/hybrid_clip/./run_hybrid_clip.py", line 542, in main
    model = FlaxHybridCLIP.from_pretrained(
  File "/home/keplab/.local/lib/python3.10/site-packages/transformers/modeling_flax_utils.py", line 900, in from_pretrained
    model = cls(config, *model_args, _do_init=_do_init, **model_kwargs)
  File "/mnt/Storage_2/Personal/Lakatos_Gabor/hybrid_clip/modeling_hybrid_clip.py", line 148, in __init__
    module = self.module_class(config=config, dtype=dtype, **kwargs)
  File "/home/keplab/.local/lib/python3.10/site-packages/flax/linen/kw_only_dataclasses.py", line 233, in init_wrapper
    dataclass_init(self, *args, **kwargs)
TypeError: FlaxHybridCLIPModule.__init__() got an unexpected keyword argument '_do_init'

Have you got any Idee, what is it problem?

Thank you!

**Comment by vinid** [comment]
Hello!

Ifrc, the `_do_init` problem is an error that comes from the transformers version used.

I'd suggest using: https://github.com/huggingface/transformers/tree/main/examples/pytorch/contrastive-image-text

**Comment by lakatosgabor** [comment]
@vinid thanks your fast answer!
