### ISSUE TITLE
Can't include model as per HuggingFace instructions

### ISSUE THREAD

**Issue by amessina71** [clip-italian/clip-italian#6]
Hello,
just trying to follow instructions posted on HuggingFace:
from transformers import AutoTokenizer, HybridCLIP
tokenizer = AutoTokenizer.from_pretrained("clip-italian/clip-italian")
model = HybridCLIP.from_pretrained("clip-italian/clip-italian")

on a fresh installation of transformers library.

Here the result:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-84edc6cdc1ae> in <module>
----> 1 from transformers import AutoTokenizer, HybridCLIP
      2 tokenizer = AutoTokenizer.from_pretrained("clip-italian/clip-italian")
      3 model = HybridCLIP.from_pretrained("clip-italian/clip-italian")

ImportError: cannot import name 'HybridCLIP'

**Comment by vinid** [comment]
Hello!

you might want to look at our [colab](https://colab.research.google.com/drive/1bLVwVKpAndpEDHqjzxVPr_9nGrSbuOQd?usp=sharing) to see how we load the model.

You'll see that we download specific python files from the HF repo:

```
!wget -q -N https://github.com/huggingface/transformers/raw/master/examples/research_projects/jax-projects/hybrid_clip/modeling_hybrid_clip.py
!wget -q -N https://github.com/huggingface/transformers/raw/master/examples/research_projects/jax-projects/hybrid_clip/configuration_hybrid_clip.py
```
