### ISSUE TITLE
Differences from Making Monolingual Sentence Embeddings Multilingual using Knowledge Distillation

### ISSUE THREAD

**Issue by ZiboZ** [clip-italian/clip-italian#7]
Awesome Work! I have read your blog, but the translation part confused me a little bit. The paper "Making Monolingual Sentence Embeddings Multilingual using Knowledge Distillation", adopts distillation to enforce the translated textual embedding for the produced by "student model" to be same with the embedding produced by "teacher model" for source English texts. As you did not introduce new (image text) pair, but only translations of original English text, may be this work will end up the same place as the beforementioned method?

**Comment by vinid** [comment]
Hello and thank you very much!

as we do not know what has been used to train CLIP, we cannot be sure if the data we have been using was included in the original model.

Also, consider that some of our captions (~700k) are from the WIT dataset that is in Italian.
