### ISSUE TITLE
Lenght of the text to be embedded

### ISSUE THREAD

**Issue by enrico310786** [clip-italian/clip-italian#8]
Hi,

great work! Just a question: 
Is there a maximum length for the text we want to embed? I know that CLIP takes a text with a maximum number of 76 tokens.

Thanks, Enrico

**Comment by vinid** [comment]
Hello and thanks!!

I quickly checked the training script and our max len is 96 tokens!

Hope this helps :)

**Comment by enrico310786** [comment]
Hi, thanks for the answer. 

I tried to embed a very long sentence, with more than 96 tokens. It works, without raising any exception.  The processor gives to me a tensor of size torch.Size([1, 312]). Thus, this is given to the function 
get_text_features( input_ids=input_ids, attention_mask=attention_mask) to obtain the embedding. And it works!

Do you know if the model uses all the tokens up to 96 and then cutting all the following one? Or it works in some other way? For example by averaging all the embeddings of the sentences of 96 tokens in order to obtain a single final embedding. I need to find the embedding of a generic sentence which can be indefinitely long. So I would like to find a strategy that allows me to deal with sentences with more than 96 tokens.

Thanks again, Enrico

**Comment by vinid** [comment]
Yes! we apply truncation. See [here](https://github.com/clip-italian/clip-italian/blob/master/hybrid_clip/run_hybrid_clip.py#L592)

I don't think there's an exact strategy to embed longer sentences in this context as the length is fixed. You could do as you suggested (average of sentence embeddings), but I am not sure about the quality of the final representation. The only other way to do this is to retrain the model.

Take a look at this [tutorial](https://colab.research.google.com/drive/13DCWQnWZksRZnnyLmw_M_XYGgDXdMbdJ?usp=sharing#scrollTo=DhvGMu-erI6C) if you want to extract the embeddings

**Comment by enrico310786** [comment]
Ok, thanks to confirm about the truncation.

**Comment by karndeepsingh** [comment]
> Ok, thanks to confirm about the truncation.

@enrico310786 Hi,
How did you train on GPU device? I am getting error of “Missing XLA configuration” which is executed from internal torch_xla library.

please share your code also help me to remove the error.

thanks

**Comment by enrico310786** [comment]
Hi, 

i am sorry but i am not training the model. I just make inference on the already trained models.

**Comment by karndeepsingh** [comment]
> Hi,
> 
> i am sorry but i am not training the model. I just make inference on the already trained models.

Oh! Thanks for answering @enrico310786 

Would be waiting for @vinid’s reply to help me understand how I can train CLIP model on GPU using the code mentioned in repository.

**Comment by vinid** [comment]
Hello @karndeepsingh!

I don't think I have an easy solution to this problem. Since we used the original HF scripts [https://github.com/huggingface/transformers/tree/main/examples/research_projects/jax-projects/hybrid_clip](https://github.com/huggingface/transformers/tree/main/examples/research_projects/jax-projects/hybrid_clip) you might be able to open a PR there to see if their script is compatible with GPU training / if there are some adjustments to do.
